import Foundation

/// Fixed, pre-written supportive message shown when `Entry.crisisFlag` is
/// true.
///
/// Per PRD §5/§6, this is deliberately **not** generated by the LLM — it's a
/// constant, so its tone and content are fully controlled, reviewable, and
/// consistent. The app states up front it isn't a therapist and doesn't
/// attempt counseling (PRD §6).
enum CrisisResponse {
    static let fixedMessage = """
    Thank you for sharing what's on your mind. What you're feeling matters, and you don't have to carry it alone.

    If you're in crisis or thinking about harming yourself, please reach out to someone who can help right now:

    - In the US: call or text 988 (Suicide & Crisis Lifeline)
    - Outside the US: please look up your local crisis line, or contact emergency services

    You can also reach out to someone you trust — a friend, family member, or doctor.

    This entry has been saved as you wrote it, but it hasn't been summarized or analyzed. I'm not a therapist, so I won't try to interpret or advise on what you've shared — it's just here for you.
    """
}
